### PR TITLE
a biblatex parser (#31)

### PR DESCRIPTION
**Pull request by maieul**
As promiss, as solution for #31.

(Maybe you would have to change the preamble, I don't know your convention)

### CODE REVIEW

**Comment by cweiske** [comment]
Could you please fix the issues mentioned by travis-ci?

```
[ERROR]   Language file contains an PHP end marker at EOF!
[ERROR]   Language file contains no newline at EOF!
[ERROR]   Language file contains trailing whitespace at EOL!
[NOTICE]  Language file contains unescaped tabulator chars (probably for indentation)!
[WARNING] Language file does not contain a specification of the release version!
```

**Comment by maieul** [comment]
I have did it for the first problems, but I don't understand how should I add the release version.

(And how should I see the list of problem?)

**Comment by cweiske** [comment]
> And how should I see the list of problem?

There is a "Details" button  besides "The Travis CI build failed". Click on it. Then click on any PHP version listed on  travis and you'll see the log.

```
[ERROR]   Language file contains trailing empty line before EOF!
[ERROR]   Language file contains trailing whitespace at EOL!
[NOTICE]  Language file contains unescaped tabulator chars (probably for indentation)!
[NOTICE]  Language file contains irregular indentation (other than 4 spaces per indentation level)!
```

**Comment by maieul** [comment]
Ok, all check have passed. I will push a new pull request, will all the "correction commit" merged in one.

**Pull request closed without merging**
