### PR TITLE
Add CSH language file

### PR DESCRIPTION
**Pull request by apjanke**
Would you accept a CSH/TCSH language definition file?

The [Open MPI website](https://www.open-mpi.org/) uses GeSHi for highlighting and has some CSH snippets. They're currently styled using the `bash` highlighter; would be nice if there was a CSH highlighter so we could get them just right.

### CODE REVIEW

**Comment by splitbrain** [comment]
@BenBE looks like there went something wrong on travis. Can you trigger a rebuild please?

**Comment by splitbrain** [comment]
The language file seems to contain a whole lot of non-CSH related commands (like apache, git, etc). I don't think they should be in here.

**Comment by apjanke** [comment]
I'm just following the example of the existing `bash.php`, which has a ton of these common commands: https://github.com/GeSHi/geshi-1.0/blob/5861c58981244ab6ee0dd337f096ff14bf15b1eb/src/geshi/bash.php#L95-L367. (Personally, I think it makes more sense to not have them.)

I can remove if you'd prefer. Would you also want a PR removing them from the Bash scheme?

**Comment by splitbrain** [comment]
huh. weird. I never noticed. I would say those shouldn't be there (neither in bash nor csh). Typical shell programming tools like `sed` or `awk` would be okay I'd think, but the rest should go IMO. @BenBE what do you think?

**Comment by BenBE** [comment]
I think having the common commands in there is kinda beneficial to average users as most snippets that use this language file are e.g. on blogs explaining things and would look rather strange if half of the commands suddenly were missing markup. What I could agree (but IIRC this is already the case) would be to have them in a separate group, thus build-ins, POSIX and other typical shell commands and such extra utilities were actually different groups.

Which brings up another discussion: What about sharing of keywords across languages? Like: Having such a utility program list in bash and tcsh would be rather nice to have in one place, instead of maintaining them one for each language file (bash, tcsh, zsh, ...).

**Comment by apjanke** [comment]
I think they are separate already: KEYWORDS group 1 and 3 are builtins; KEYWORDS group 2 is the external commands.

>  What about sharing of keywords across languages? Like: Having such a utility program list in bash and tcsh would be rather nice to have in one place, instead of maintaining them one for each language file (bash, tcsh, zsh, ...)

I think that's a great idea. I don't know enough PHP to help make it happen, though.

**Pull request closed without merging**
